# pylint: disable=invalid-name
# pylint: disable=pointless-string-statement
# pylint: disable=too-few-public-methods

"""
This is the module for the Personnel class, and is designed to
document which personnel in the sandbox are authorizing
disabling of printers at the sandbox
"""
import pickle

PERSONNEL_INFO_CSV = 'Personnel Info.csv'
PERSONNEL_INFO_TXT = 'Personnel Info.txt'

class Personnel(object):
    """
    Class for the personnel at the sandbox, and can be used to
    authorize access to the printer usage
    """
    def __init__(self, name, pin):
        """
        Args:
            name: str
                The name of the Personnel, saved for security reasons

            pin: str
                The password pin of the indiviual. This is hashed using
                a md5 algorithm and it's hash is what is used to check
        """
        self.name = name
        self.pin = Personnel._getHash(pin)
        self._save()

    def __str__(self):
        """
        magic function to convert the Personnel Object to a string
        """
        return '{0}, {1}'.format(self.name, self.pin)

    def __repr__(self):
        """
        magic function to represent the Personnel Object
        """
        return '{0}, {1}'.format(self.name, self.pin)

    def __eq__(self, pin: str):
        """
        Function to check if the pin matches the pin of this object
        """
        if not isinstance(pin, str):
            raise TypeError("Expected str, got", type(pin))

        else:
            return self.pin == self._getHash(pin)

    @staticmethod
    def _getHash(pin):
        import hashlib
        """
        Function used to return hash generated by the pin
        This is a static method as it is is independant of all
        other properties of the class

        Args:
            pin :str
                The pin that the user has given
        """
        pin = pin.encode('utf-8')
        hashVal = hashlib.md5(pin).hexdigest()

        return hashVal

    @staticmethod
    def isPinPresent(pin, personnel_list_file=PERSONNEL_INFO_TXT):
        """
        Function to check if the pin is present in the hash of the pins
        """
        hashed_pin = Personnel._getHash(pin)
        try:
            with open(personnel_list_file, 'rb') as file_object:
                return Personnel.CheckInFile(file_object, hashed_pin)
        except FileNotFoundError:
            print('File Not Found, returning False')
            return False

    @staticmethod
    def CheckInFile(file_object, hashed_pin):
        while True:
            try:
                user_details = pickle.load(file_object)
                if hashed_pin == user_details.pin:
                    return True
            except EOFError:
                return False

    @staticmethod
    def addNewPersonnel(name, pin):
        """
        Function to add a new personnel. It first checks if the personnel had a
        pin occour before, and asks to change it.
        """
        if Personnel.isPinPresent(pin):
            raise IndexError("Pin has been used before, please enter another pin")
        else:
            Personnel(name, pin)

    def _save(self):
        """
        Saving the Personnel information for later usage
        """
        with open(PERSONNEL_INFO_CSV, 'a') as file_object:
            file_object.write(str(self) + '\n')

        with open(PERSONNEL_INFO_TXT, 'ab') as file_object:
            pickle.dump(self, file_object)

def main():
    """
    Main function to display the documentation for the class defined
    """
    while True:
        try:
            name = input('Enter the new personnel name: ')
            pin = input('Enter the new personnel pin: ')
            Personnel.addNewPersonnel(name, pin)
        except IndexError:
            continue

if __name__ == '__main__':
    main()
