from PyQt5.QtGui import QFont

DEFAULT_LABEL_FONT_FAMILY = "OCR A Extended"
DEFAULT_PUSHBUTTON_FONT_FAMILY = "OCR A Extended"

DEFAULT_LABEL_FONT = QFont(DEFAULT_LABEL_FONT_FAMILY)
DEFAULT_LABEL_FONT.setPointSize(15)

DEFAULT_DIALOG_FONT = QFont()
DEFAULT_DIALOG_FONT.setBold(False)
DEFAULT_DIALOG_FONT.setWeight(50)

DEFAULT_PUSHBUTTON_FONT = QFont(DEFAULT_PUSHBUTTON_FONT_FAMILY)
DEFAULT_PUSHBUTTON_FONT.setPointSize(12)

DEFAULT_PUSHBUTTON_FONT_EMPHASIS = QFont(DEFAULT_PUSHBUTTON_FONT_FAMILY)
DEFAULT_PUSHBUTTON_FONT_EMPHASIS.setPointSize(12)
DEFAULT_PUSHBUTTON_FONT_EMPHASIS.setItalic(True)
DEFAULT_PUSHBUTTON_FONT_EMPHASIS.setUnderline(True)

DEFAULT_PUSHBUTTON_STRONG_FONT = QFont(DEFAULT_PUSHBUTTON_FONT_FAMILY)
DEFAULT_PUSHBUTTON_STRONG_FONT.setPointSize(12)
DEFAULT_PUSHBUTTON_STRONG_FONT.setBold(True)
DEFAULT_PUSHBUTTON_STRONG_FONT.setItalic(False)

DEFAULT_PUSHBUTTON_STRONG_EMPHASIS_FONT = QFont(DEFAULT_PUSHBUTTON_FONT_FAMILY)
DEFAULT_PUSHBUTTON_STRONG_EMPHASIS_FONT.setPointSize(12)
DEFAULT_PUSHBUTTON_STRONG_EMPHASIS_FONT.setBold(True)
DEFAULT_PUSHBUTTON_STRONG_EMPHASIS_FONT.setItalic(True)
DEFAULT_PUSHBUTTON_STRONG_EMPHASIS_FONT.setWeight(75)
