# Default Texts
DEFAULT_DIALOG_OBJECT_NAME: str = "Dialog"

DEFAULT_TEXT_lbl_St1_DisplayPrinterNumber: str = "Printer Number: <?PrinterNumber?>"
DEFAULT_TEXT_pb_St1_StartPrint: str = "Click me\nStart your print!"

DEFAULT_TEXT_lbl_St2_StudentIDDisplay: str = "Enter your Student ID: "
DEFAULT_TEXT_pb_St2_Num2: str = "2"
DEFAULT_TEXT_pb_St2_Num1: str = "1"
DEFAULT_TEXT_pb_St2_Num9: str = "9"
DEFAULT_TEXT_pb_St2_Num3: str = "3"
DEFAULT_TEXT_pb_St2_Num6: str = "6"
DEFAULT_TEXT_pb_St2_Num4: str = "4"
DEFAULT_TEXT_pb_St2_Num5: str = "5"
DEFAULT_TEXT_pb_St2_Num8: str = "8"
DEFAULT_TEXT_pb_St2_Num7: str = "7"
DEFAULT_TEXT_pb_St2_Num0: str = "0"
DEFAULT_TEXT_pb_St2_Go_Back: str = "<- Go Back"

DEFAULT_TEXT_lbl_St4_TimeRemaining: str = "Time Remaining: <?TimeRemaining?>"
DEFAULT_TEXT_pb_St4_CancelPrint: str = "Cancel Print"
DEFAULT_TEXT_pb_St4_MakeChanges: str = "Make Changes"

DEFAULT_TEXT_lbl_St5_StudentOrPersonnelID: str = "Re-Enter Student ID: "
DEFAULT_TEXT_pb_St2_BackSpace: str = "<-"
DEFAULT_TEXT_pb_St2_Enter: str = "Enter"
DEFAULT_TEXT_pb_St5_Enter: str = "Enter"
DEFAULT_TEXT_pb_St5_Num8: str = "8"
DEFAULT_TEXT_pb_St5_BackSpace: str = "<-"
DEFAULT_TEXT_pb_St5_Num6: str = "6"
DEFAULT_TEXT_pb_St5_Num3: str = "3"
DEFAULT_TEXT_pb_St5_Num7: str = "7"
DEFAULT_TEXT_pb_St5_Num0: str = "0"
DEFAULT_TEXT_pb_St5_Num2: str = "2"
DEFAULT_TEXT_pb_St5_Num9: str = "9"
DEFAULT_TEXT_pb_St5_Num1: str = "1"
DEFAULT_TEXT_pb_St5_Num5: str = "5"
DEFAULT_TEXT_pb_St5_Num4: str = "4"
DEFAULT_TEXT_pb_St5_Go_Back: str = "<- Go Back"
