# Default Style Sheets
DEFAULT_DIALOG_STYLESHEET: str = "background: rgb(255, 255, 255)"

DEFAULT_STYLE_SHEET_lbl_St1_DisplayPrinterNumber: str = "QWidget{color: rgba(0,0,0,100%); background:transparent}"
DEFAULT_STYLE_SHEET_pb_St1_StartPrint: str = ""

DEFAULT_STYLE_SHEET_lbl_St2_StudentIDDisplay: str = "QWidget{color: rgba(0,0,0,100%); background:transparent}"
DEFAULT_STYLE_SHEET_pb_St2_Num0: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num1: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num2: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num3: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num4: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num5: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num6: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num7: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num8: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Num9: str = ""
DEFAULT_STYLE_SHEET_pb_St2_BackSpace: str = ""
DEFAULT_STYLE_SHEET_pb_St2_Enter: str = ""

DEFAULT_STYLE_SHEET_lbl_St4_TimeRemaining: str = "QWidget{color: rgba(0,0,0,100%); background:transparent}"
DEFAULT_STYLE_SHEET_pb_St4_CancelPrint: str = ""
DEFAULT_STYLE_SHEET_pb_St4_MakeChanges: str = ""

DEFAULT_STYLE_SHEET_lbl_St5_StudentOrPersonnelID: str = "QWidget{color: rgba(0,0,0,100%); background:transparent}"
DEFAULT_STYLE_SHEET_pb_St5_Num0: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num1: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num2: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num3: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num4: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num5: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num6: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num7: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num8: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Num9: str = ""
DEFAULT_STYLE_SHEET_pb_St5_BackSpace: str = ""
DEFAULT_STYLE_SHEET_pb_St5_Enter: str = ""
